disabled_rules:
  - multiple_closures_with_trailing_closure

included:
- Mongli/Source

excluded:
- Pods

force_try:
  severity: warning

identifier_name:
  min_length:
    error: 3
  excluded:
    - vc
    - id
    - in
    - ok
    - i
